version: "2"

run:
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - gosec
    - staticcheck
    - revive
  settings:
    revive:
      rules:
        - name: var-naming
        - name: package-comments
        - name: exported
    gosec:
      excludes:
        - G110
        - G115
        - G301
        - G304
        - G305
        - G402
        - G602
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
